#!/bin/zsh

#Evita que se apruebe el commit si incluye ciertas palabras
RESTORE='\033[0m'
RED='\033[00;31m'
YELLOW='\033[00;33m'
BLUE='\033[00;34m'

FORBIDDEN=( 'TODO:' 'DO NOT COMMIT' 'println' 'todo' 'print' 'nochekin')
FOUND=''

for j in "${FORBIDDEN[@]}"
do
  for i in `git diff --cached --name-only`
  do
    if echo `git show :$i` | rg -q "$j"; then
      FOUND+="${BLUE}$i ${RED}contains ${RESTORE}\"$j\"${RESTORE}\n"
    fi
  done
done

# if FOUND is not empty, REJECT the COMMIT, PRINT the results (colorful-like)

if [[ ! -z $FOUND ]]; then
  printf "${YELLOW}COMMIT REJECTED\n"
  printf "$FOUND"
  exit 1
fi

exit 0
#from: https://stackoverflow.com/questions/24968112/searching-files-with-pre-commit
